<?php

namespace FYP\Database\Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FYPDatabaseDocumentsWordHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lemma'])) {
            $value = $data['lemma'];
            $return = (string) $value;
            $this->class->reflFields['lemma']->setValue($document, $return);
            $hydratedData['lemma'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['pos'])) {
            $value = $data['pos'];
            $return = (string) $value;
            $this->class->reflFields['pos']->setValue($document, $return);
            $hydratedData['pos'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['is_wordnet'])) {
            $value = $data['is_wordnet'];
            $return = (string) $value;
            $this->class->reflFields['isWordnet']->setValue($document, $return);
            $hydratedData['isWordnet'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['is_wikipedia'])) {
            $value = $data['is_wikipedia'];
            $return = (string) $value;
            $this->class->reflFields['isWikipedia']->setValue($document, $return);
            $hydratedData['isWikipedia'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['neo4j_id'])) {
            $value = $data['neo4j_id'];
            $return = (int) $value;
            $this->class->reflFields['neo4jId']->setValue($document, $return);
            $hydratedData['neo4jId'] = $return;
        }
        return $hydratedData;
    }
}